auto_init: true
enable_check_ready: true
net_card_name: "enp4s0"

enable_arms: true
enable_legs: true
enable_imu: true
enable_hands: false
enable_6dof: false
enable_head: true
enable_waist: true
enable_waist_home: false
enable_head_home: false
enable_power: false

# 0 - standard, 1 - extended, 2 - time_sharing_mixed
slave_mode:
  - 0   # left_leg
  - 0   # right_leg
  - 0   # xsens_imu
