# /*
#  * @Author: HuangYongshan(shawn.huang@x-humanoid.com) 
#  * @Date: 2024-02-20 
#  * @Last Modified by:   HuangYongshan(shawn.huang@x-humanoid.com) 
#  * @Last Modified time: 2024-02-20 
#  */

### 参数对应的物理含义：[x-y-z, r-p-y]

############# ============================ gaitMpc-Start ============================ #############
Q_xLip: [1000.0,   1000.0,    1000.,   1000.] 
R_regu: [1.,   1.]  
############# ============================= gaitMpc-End ============================= #############

############# ============================ Start ============================ #############
## 质心位置、线动量、角动量跟踪
kp_comPos: [50.0,     50.0,     100.0] 
kd_comMt:  [7.0,      5.0,      10.0,     5.0,      5.0,      5.0] 
# w_comMt:   [100.0,    100.0,    100.0,    100.0,    100.0,    100.0] 
w_comMt:   [0.0,    0.0,    0.0,    0.0,    0.0,    0.0] 

## 足地接触约束
############# w_footContact: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 

## SE3位姿跟踪
# kp_base_se3: [150.0,    150.0,    300.0,    300.0,    300.0,    50.0]   
# kd_base_se3: [25.0,     30.0,     50.0,     10.0,     35.0,     30.0]
# w_base_se3:  [100.0,    100.0,    100.0,    100.0,    100.0,    100.0]
kp_base_se3: [200.0,    150.0,    500.0,    300.0,    300.0,    50.0]   
kd_base_se3: [30.0,     30.0,     50.0,     50.0,     50.0,     100.0]
w_base_se3:  [100.0,    100.0,    800.0,    500.0,    500.0,    100.0]

kp_leg_se3: [200.0,    200.0,    200.0,    100.0,    100.0,    100.0 ]
kd_leg_se3: [15.0,     15.0,     15.0,     6.0,      6.0,      6.0   ]
w_leg_se3:  [1000.0,   1000.0,   1000.0,   1000.0,   1000.0,   1000.0]

############## kp_arm_se3: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
############## kd_arm_se3: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
############## w_arm_se3:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

### PD
############## jointP << 1000.0,  1000.0,  502.2,  297.6,  4.0,  1.0; 
############## jointD << 10.0,    10.0,    10.0,   10.0,   0.1,  0.025; 
# kp_leg: [1000.0,  1000.0,  502.2,  297.6,  4.0,  1.0]
# kd_leg: [10.0,    10.0,    10.0,   10.0,   0.1,  0.025]
# kp_waist: [0.0]
# kd_waist: [0.0]
# kp_arm: [0.0,  0.0,  0.0]
# kd_arm: [0.0,  0.0,  0.0]

### sim parameters
kp_leg: [1000.0,  1000.0,  502.2,  297.6,  4.0,  1.0]
kd_leg: [10.0,    10.0,    10.0,   10.0,   0.1,  0.025]
kp_waist: [0.0]
kd_waist: [0.0]
kp_arm: [0.0,  0.0,  0.0]
kd_arm: [0.0,  0.0,  0.0]

### deploy parameters
# kp_leg: [1000., 1000., 1200., 1000., 200., 200.]
# kd_leg: [20.,   20.,   20.,   20.,   4.,   4.]
# kp_waist: [50.0]
# kd_waist: [1.0]
# kp_arm: [50.,   50.,   50.]
# kd_arm: [1.,    1.,    1.]

## 足底力跟踪
w_footForce_track: [0.1,     0.1,     0.001,    0.1,    0.1,    0.1] 
w_footForce_rate:  [0.001,   0.001,   0.0001,   0.001,  0.001,  0.001] 

## 关节轨迹跟踪
kp_leg_jnt: [0.0,    0.0,    0.0,    0.0,    0.0,    0.0]
kd_leg_jnt: [0.0,    0.0,    0.0,    0.0,    0.0,    0.0]
w_leg_jnt:  [0.0,    0.0,    0.0,    0.0,    0.0,    0.0]

kp_waist_jnt: [100.0]
kd_waist_jnt: [10.0]
w_waist_jnt:  [0.1]

kp_arm_jnt: [100.0,   100.0,   100.0]
kd_arm_jnt: [10.0,    10.0,    10.0]
w_arm_jnt:  [0.1,     0.1,     0.1]

## 地反力和地反力矩上下限制
grf_max: [ 500.,  500.,  1000.,  20.,  20.,  20.,]
grf_min: [-500., -500.,  50.,   -20., -20., -20.,]

## 关节力矩上下限约束
tau_max_leg: [ 150.0,  90.0,  150.0,  150.0,  60.0,  30.0]
tau_min_leg: [-150.0, -90.0, -150.0, -150.0, -60.0, -30.0] 

tau_max_waist: [ 100.0] 
tau_min_waist: [-100.0] 

tau_max_arm: [ 36.0,  36.0,  36.0]
tau_min_arm: [-36.0, -36.0, -36.0]

## 关节速度上下限约束
vel_max_leg: [ 12.,  14.,  12.,  12.,  7.8,  7.8]
vel_min_leg: [-12., -14., -12., -12., -7.8, -7.8] 

vel_max_waist: [ 100.] 
vel_min_waist: [-100.] 

vel_max_arm: [ 7.8,  7.8,  7.8]
vel_min_arm: [-7.8, -7.8, -7.8]

## 关节加速度上下限约束
acc_max_leg: [ 100.,  100.,  100.,  100.,  100.,  100.]
acc_min_leg: [-100., -100., -100., -100., -100., -100.] 

acc_max_waist: [ 100.] 
acc_min_waist: [-100.] 

acc_max_arm: [ 100.,  100.,  100.]
acc_min_arm: [-100., -100., -100.]

############# ======================================================== #############
############# ======================================================== #############
############# ======================================================== #############
# period: 0.4
# period_d: 0.4
# period2: 0.3
# early_terminate: 0.9
# height: 0.74
# foot_height: 0.12
# com_x: 0.0002
# com_y: 0.0
# com_z: 0.01582
# vel_y_osci: 0.32
# vel_y_vari: 0.0
# vel_x_FFratio: 1.1
# vel_y_FFratio: 1.0
# vel_x_FBratio: 1.0
# vel_y_FBratio: 1.0
# x_bound: 0.45
# y_bound_in: 0.08
# y_bound_out: 0.25
# z_bound: 0.03
# rx_factor: 100.0
# ry_factor: 100.0
# px_factor: 0.0
# py_factor: 0.0

######【对应lite01的参数】
# period: 0.4
# period_d: 0.4
# period2: 0.3
# early_terminate: 0.95
# height: 0.74
# foot_height: 0.06
# com_x: 0.02 
# com_y: 0.0
# com_z: -0.0527
# vel_y_osci: 0.3
# vel_y_vari: 0.08
# vel_x_FFratio: 1.0
# vel_y_FFratio: 1.0
# vel_x_FBratio: 1.0
# vel_y_FBratio: 1.0
# x_bound: 0.24
# y_bound_in: 0.08
# y_bound_out: 0.3
# z_bound: 0.03
# rx_factor: 100.0
# ry_factor: 100.0
# px_factor: 0.0
# py_factor: 0.0

######【对应Max2的参数】
period: 0.4
period_d: 0.4
period2: 0.3
early_terminate: 0.95
height: 0.88 ### TODO:
foot_height: 0.06
# com_x: -0.001 ### 带质心的行走  ### TODO: 大往后退， 小往前进
com_x: 0.042  ### TODO: 大往后退， 小往前进 版本问题，有个0.042的offset写死了，实际-0.005
com_y: -0.00     ### TODO: 版本问题，有个0.0的offset写死了，实际-0.005
com_z: -0.1558 ### TODO:
vel_y_osci: 0.3
vel_y_vari: 0.08  #mpc 0.08 版本问题，有个0.08的offset写死了，实际0.15
vel_x_FFratio: 1.0
vel_y_FFratio: 1.0
vel_x_FBratio: 1.0
vel_y_FBratio: 1.0
x_bound: 0.3
y_bound_in: 0.08
y_bound_out: 0.4
z_bound: 0.03
rx_factor: 100.0
ry_factor: 100.0
px_factor: 0.0
py_factor: 0.0
imu_offset_roll: 0.0 #1号机0.005 3号机0
imu_offset_pitch: 0.0

gain_matrix:
  row0: [180.0, 220.0, 50.0, 150.0, 150.0, 300.0]
  row1: [15.0,  20.0,  10.0, 25.0,  30.0,  50.0]
############# ======================================================== #############
############# ======================================================== #############
############# ======================================================== #############

############# =========_=================== End ============================ #############